version: "3.3"
services:
        capture:
                build:
                        context: ..
                        dockerfile: docker/capture_rs485-picoscope-capture.Dockerfile.Dockerfile
                volumes:
                        - ${DATADIR}:/data
                stdin_open: true
                tty: true
                entrypoint: ["python3", "/code/capture/rs485-picoscope-capture/code/capture_rs485_picoscope.py", "tcp://0.0.0.0:5678"]
                depends_on:
                        - fingerprinting
        demod:
                build:
                        context: ..
                        dockerfile: docker/demod_rs485-trivial-decode.Dockerfile
                volumes:
                        - ${DATADIR}:/radio
                stdin_open: true
                tty: true
                entrypoint: ["python3", "/code/demod/rs485-trivial-decode/code/decode.py", "tcp://capture:5678", "tcp://0.0.0.0:5678"]
                depends_on:
                        - fingerprinting
        fingerprinting:
                build:
                        context: ..
                        dockerfile: docker/fingerprinting_rs485-siamese.Dockerfile
                volumes:
                        - ${DATADIR}:/data
                stdin_open: true
                tty: true
                #entrypoint: ["python3", "code/fingerprinting/rs485-siamese/fingerprinter.py", "tcp://replay:5678", "tcp://0.0.0.0:5678", "/code/fingerprinting/rs485-siamese/models/rs485-siamese.h5", "/data/fingerprint-msgs-rs485.sqlite3", "FIRST"]
                entrypoint: ["python3", "code/fingerprinting/rs485-siamese/fingerprinter.py", "tcp://replay:5678", "tcp://0.0.0.0:5678", "/data/rs485-test-model.h5", "/data/fingerprint-msgs-rs485.sqlite3", "FIRST"]
#        storage-verified:
#                build:
#                        context: ..
#                        dockerfile: docker/storage_adsb-verified-msg-storage.Dockerfile
#                volumes:
#                        - ${DATADIR}:/radio
#                stdin_open: true
#                tty: true
#                entrypoint: ["python3", "/code/storage/adsb-verified-msg-storage/code/store.py", "tcp://fingerprinting:5678", "/radio/adsb-stream-compose.sqlite3", "ADS-B"]
#                depends_on:
#                        - capture
#                        - demod
#                        - filtering
#                        - fingerprinting
        visualisation:
                build:
                        context: ..
                        dockerfile: docker/visualisation_adsb-positions.Dockerfile
                ports:
                        - "5006:5006"
                volumes:
                        - ${DATADIR}:/radio
                stdin_open: true
                tty: true
                entrypoint: ["bokeh", "serve", "/code/visualisation/rs485-stats/code", "--allow-websocket-origin=localhost:5006", "--args", "--recv_connect_addr", "tcp://fingerprinting:5678", "--topic", "RS-485"]
                depends_on:
                        - fingerprinting
